resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:283a947dde8d0ee6dccaacb73703cbece8fd107c44a0b9e181dca65a341b1b63
  name: quay.io/evanshortiss/quinoa-wind-turbine
- digest: sha256:54df6e901e4349d3c35bdc2474811063115ffbb6ec7f0a2013c8089f3166ed31
  name: quay.io/rhdevelopers/quinoa-wind-turbine
